### ISSUE TITLE
Improvement of Sign Up page

### ISSUE THREAD

**Issue by vinayaksh42** [Bot-Academia/Nebula-Frontend#33]
**Is your feature request related to a problem? Please describe.**
Currently, the bottom part of the signup box is colliding with the footer. If possible we would like to fix it.

**Describe the solution you'd like**
Extra padding can be added to the bottom of the sign-up box

**Additional context**
![screencapture-localhost-3000-signup-2020-12-03-22_30_23](https://user-images.githubusercontent.com/54861487/101062033-26badd80-35b7-11eb-83f2-f65bf10ed437.png)
Current view of the sign-up page

**Comment by codewithvk** [comment]
I would like to fix this issue.

**Comment by vinayaksh42** [comment]
hey @codewithvk 
kindly join the [slack ](https://join.slack.com/t/nebulaplatform/shared_invite/zt-jixsfnrq-SdncWSwsWKq9puEXcJgHyQ)channel if you haven't yet.
You can go ahead with this issue and if you face any problem regarding the initial setup of the project or location of the files which have to be changed to fix this issue, Message me on slack.

Also, the coding period for KWOC starts from the 6th of December so I would suggest you to push your commits after 6th
