### ISSUE TITLE
 incorporating color schema on the readme

### ISSUE THREAD

**Issue by vinayaksh42** [Bot-Academia/Nebula-Frontend#34]
**Is your feature request related to a problem? Please describe.**
Documentation changes for incorporating color schema/template of the website

**Describe the solution you'd like**
The most used color scheme of the website is:
#17a2b8
it would be great if we can have this mentioned on the project readme so that it is easy for everyone to work with it

**Comment by codewithvk** [comment]
I would like to fix this issue.

**Comment by vinayaksh42** [comment]
You can go ahead with this issue
The coding period for KWOC starts from the 6th of December so I would suggest you to push your commits after 6th

**Comment by codewithvk** [comment]
Thanks, @vinayaksh42
