### ISSUE TITLE
Mention of communication channel in Readme

### ISSUE THREAD

**Issue by vinayaksh42** [Bot-Academia/Nebula-Frontend#37]
Mentioning of the communication channel (slack) in the Readme

in this way:
![chrome_J1dsnF3wEp](https://user-images.githubusercontent.com/54861487/101138358-185fd680-3636-11eb-98bb-17727a5d937c.png)

**Describe the solution you'd like**
add the slack and the link to join the slack channel in the Readme
slack link: https://join.slack.com/t/nebulaplatform/shared_invite/zt-jixsfnrq-SdncWSwsWKq9puEXcJgHyQ

**Comment by Godzilla5111** [comment]
Hey @vinayaksh42, please assign this to me, I would like to contribute!

**Comment by vinayaksh42** [comment]
sure @Godzilla5111 go ahead

**Comment by Godzilla5111** [comment]
Thanks, @vinayaksh42! I will fix it as soon as the coding period begins. Cheers!😊

**Comment by vinayaksh42** [comment]
hey @Godzilla5111 the coding period has begun.

**Comment by Godzilla5111** [comment]
Yes, I will do the fix in an hour or so and get back to you.👍🙂
