### ISSUE TITLE
Postioning of "Join Club" button

### ISSUE THREAD

**Issue by vinayaksh42** [Bot-Academia/Nebula-Frontend#38]
**Is your feature request related to a problem? Please describe.**
Currently, the "join club" button is center aligned and left in a place that is a bit wrong.

**Describe the solution you'd like**
moving it to the bottom right or left might be a better approach 
Location of file: pages -> club/_id -> index.vue (line30)

**Additional context**
![chrome_S072byW0W4](https://user-images.githubusercontent.com/54861487/101247863-c4421880-3741-11eb-8614-28fcdfa496d7.png)

**Comment by codewithvk** [comment]
Can you assign me? I am happy to work on this issue.

**Comment by vinayaksh42** [comment]
sure go ahead @codewithvk
